Changes for task 40
dulasevich/SelenuimJavaCourse pull request #4
Opened 2022-08-10 10:15 UTC by dulasevich

2022-08-12 15:24 UTC, LikBez123 requested changes

2022-08-12 15:24 UTC, LikBez123 commented on src/main/java/by/Variables.java
> +    public static By accountName = By.xpath("//div[contains(@class, 'legouser')]/a/span[@class='user-account__name']");
make it final and in uppercase

2022-08-12 15:24 UTC, LikBez123 commented on src/main/java/by/Variables.java
> +    public static By js = By.xpath("//button[@onclick='myConfirmFunction()']");
please check the names of elements

2022-08-12 15:24 UTC, LikBez123 commented on src/test/java/AlertsTest.java
> +
remove empty lines

2022-08-12 15:24 UTC, LikBez123 commented on src/test/java/AlertsTest.java
> +        driver.switchTo().alert().sendKeys(sendKeys);
`Alert alert = driver.switchTo().alert();`

2022-08-12 15:24 UTC, LikBez123 commented on src/test/java/DownloadTest.java
> +        new WebDriverWait(driver, Duration.ofSeconds(15)).
add polling every 100 mills
`Duration.ofMillis(100)`

2022-08-12 15:24 UTC, LikBez123 commented on src/test/java/LoginTest.java
> +        Thread.sleep(1000);
remove redundant` Thread.sleep()-s`
use `implicitlyWait(Duration.ofSeconds(10));`

2022-08-12 15:24 UTC, LikBez123 commented on src/test/java/MultiSelectTest.java
> +        while (select.getAllSelectedOptions().size() != 3) {
you can move this logic to separate method

2022-08-12 15:24 UTC, LikBez123 commented on src/test/java/ParamsTest.java
> +    void login (String l, String p){
use correct parameter names

2022-08-12 15:24 UTC, LikBez123 commented on src/main/java/table/User.java
> +    public User(String name, String position, String office, int age, int salary) {
`User(String name, String position, String office)`

2022-08-12 15:24 UTC, LikBez123 commented on src/test/java/TableUserTest.java
> +        List<WebElement> names = driver.findElements(userName);
```
@Test
    void tableTest() {
        TablePage tablePage = new TablePage(driver);
        tablePage.navigateToBaseURL();
        tablePage.selectOptionFromDropDown("10");
        List<Person> allPeopleWithAgeAndSalary = tablePage.getUsersWithConditions(30, 200000);
        for (int i = 0; i <= allPeopleWithAgeAndSalary.size() - 1; i++) {
            Person index = allPeopleWithAgeAndSalary.get(i);
            System.out.println(index);
        }
    }
```

```
public List<Person> getUsersWithConditions(int minAge, int maxSalary) {
        List<Person> persons = new ArrayList<>();
        do {
            WebElement nextButton = driver.findElement(By.cssSelector(".next"));
            collectUsersWithConditions(persons, minAge, maxSalary);
            nextButton.click();
        } while (driver.findElement(By.cssSelector(".next")).getAttribute("class").contains("disabled"));
        return persons;
    }

    private void collectUsersWithConditions(List<Person> users, int minAge, int maxSalary) {
        List<WebElement> rows = driver.findElements(By.cssSelector("tbody tr"));
        rows.forEach(row -> {
            int salary = Integer.parseInt(row.findElement(By.xpath("td[6]")).getAttribute("data-order"));
            int age = Integer.parseInt(row.findElement(By.xpath("td[4]")).getText());
            if (salary <= maxSalary && age > minAge) {
                String name = row.findElement(By.xpath("td[1]")).getText();
                String position = row.findElement(By.xpath("td[2]")).getText();
                String office = row.findElement(By.xpath("td[3]")).getText();
                users.add(new Person(name, position, office));
            }
        });
    }
```

2022-08-15 08:27 UTC, dulasevich commented
For the latest commit - 'Changes for task 40 - updates per request' I have small question about TableUserTest, the solution that you provided with table rows and Next button.

2022-08-15 13:04 UTC, LikBez123 requested changes

2022-08-15 13:04 UTC, LikBez123 commented on src/test/java/MultiSelectTest.java
> +    private Select randomThreeStatesSelection() {
according to the java convention, it is better to call this method starting with the verb. Ex.: `selectStates()`, `selectThreeRandomStates()`

2022-08-15 13:04 UTC, LikBez123 commented on src/test/java/MultiSelectTest.java
> +        List<String> allOptions = randomThreeStatesSelection().getOptions().stream()
it is better to define select in the test and not use the `randomThreeStatesSelection()` method to get an instance of the Select class

2022-08-15 13:04 UTC, LikBez123 commented on src/main/java/by/Variables.java
> +    public final static By TABLE_POSITION = By.xpath("td[2]");
.//td[2]

2022-08-15 13:04 UTC, LikBez123 commented on src/test/java/MultiSelectTest.java
> +        Assertions.assertTrue(allOptions.containsAll(selectedOptions));
please check the test logic

2022-08-16 09:13 UTC, dulasevich commented
написал не через стримы, чтобы не просто копировать твое решение, которое показал вчера вечером, ну и через стримы пока сложнее дается) 
.//td[2] для Variables сработало, но я бы все равно обсудил в след раз на всякий случай)

2022-08-16 10:26 UTC, LikBez123 requested changes

2022-08-16 10:26 UTC, LikBez123 commented on src/test/java/MultiSelectTest.java
> +        select.getOptions();
redundant line. Remove it

2022-08-16 10:26 UTC, LikBez123 commented on src/test/java/MultiSelectTest.java
> +        return expectedStates;
your logic is able to return a collection with the same elements. It is a mistake

2022-08-16 11:17 UTC, LikBez123 approved these changes

2022-08-16 11:24 UTC, merged